#mind ua is not present
https://mind.ua/editorial
:)

 cite are missing https://mind.ua/ru/publications/20183057-ostorozhno-facebook-pochemu-voznik-skandal-s-ispolzovaniem-personalnyh-dannyh

https://mind.ua/education/899-programa-ukrainian-mba
this need to be fixed

 https://mind.ua/news/20194347-zapravilas-u-prozorro-skilki-vitratila-derzhava-byudzhetnih-koshtiv-na-palne
 Figcaptions are missing while they are possible to indentfiy.
 Html struct:
 http://prntscr.com/mu5ar6

 https://mind.ua/news/20194293-youcontrol-tretinu-dohodu-biznesu-dnipropetrovshchini-ta-odeshchini-generuyut-ofshorni-kompaniyi
 h6 maybe figcapt


!nomedia https://mind.ua/publications/20191403-pridbati-kvartiru-i-ne-prograti-7-pomilok-pokupciv-zhitla-na-vtorinnomu-rinku

Looks like i and all other contestant messed up with this page because of 404 media not found err.
@admin, what we should do in such case?

#партнерський матеріал
is like Information Is on advertise rights.
important to keep this link for user.

This post is all about Bulding company
Label "Partnership content" should be preserved. (check my template)
User deserves to know, what content was created on "advertise partnership"

https://mind.ua/news/20193030-innovacijnij-park-unit-city-zbilshili-vdvichi-ta-vidkrili-tretij-biznes-kampus


https://mind.ua/news/20194388-u-bryusseli-projde-festival-ukrayinskoyi-kulturi-ukrayinska-vesna

"we cannot check every page just one page with this issue so it is not critical..."
True, but this current template will fall with err. each time,
when  site author adds table in div class="post__frame"

You choose to highlight this div as blockqoute. Same as me. Cool!
But it is possible to not fail with error such cases:
<div class="post__frame">
    <table>...</table>
</div>

You may check other template for this page.
no media found

https://mind.ua/publications/20191403-pridbati-kvartiru-i-ne-prograti-7-pomilok-pokupciv-zhitla-na-vtorinnomu-rinku

<div class="post__frame">
    <table>...</table>
</div>
https://mind.ua/openmind/20189763-chomu-venchurnij-kapital-ominae-ukrayinskij-rinok
should be preserved

! blockqoute nested!
https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya
sunny with uzlVer!

Page should be supported. Check my template.
Looks like you overplaying with blockqoute.
https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya

#old 2 aut
#test
https://mind.ua/openmind/20194151-u-zoni-turbulentnosti-yak-koncesiya-dopomozhe-ukrayinskim-aeroportam


Too much text with large font-size.
Definetly figcaption and it is possible to support. check my template.
!FIGcaption
fl:
https://mind.ua/openmind/20175907-hochu-selfi-ale-fotokameru-shche-ne-vinajshli-istoriya-viniknennya-ukrayinskogo-portretu


figc
https://mind.ua/en/publications/20190743-power-trends-what-energy-projects-are-worth-investing-in

my bug
https://www.g4media.ro/video-documente-deputatul-florin-roman-acuzatii-grave-la-adresa-psd-cu-privile-la-chelutirea-subventiei-de-la-stat-ii-acuz-deschis-de-spalare-de-bani-si-deturnare-de-fonduri.html
https://www.g4media.ro/episcopia-husilor-anunta-ca-a-luat-act-de-condamnarea-preotilor-care-l-au-santajat-pe-fostul-episcop-foto-acesta-din-urma-a-fost-acuzat-de-relatii-sexuale-cu-un-elev-de-seminar.html

should be precent cite
https://mind.ua/publications/20180681-tiha-gavan-shcho-dp-world-pridbala-v-portu-yuzhnij

https://mind.ua/openmind/20177349-korupciya-po-kiyivski-shcho-yavlyali-soboyu-habari-chasiv-getmanshchini
_fr right
https://mind.ua/openmind/20177349-korupciya-po-kiyivski-shcho-yavlyali-soboyu-habari-chasiv-getmanshchini

UzVer template better https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven

https://mind.ua/questions/385-integrities

fk. kostia
https://www.g4media.ro/protocolul-tinut-secret-de-tudorel-toader-ministrul-justitiei-refuza-sa-faca-publice-numele-membrilor-comisiei-sipa.html

https://mind.ua/questions/385-integrities#3
#marked text
https://mind.ua/ru/publications/20193696-kilovatty-pod-zashchitoj-kak-zastrahovat-elektromobil
#marked text
https://mind.ua/ru/publications/20192337-cena-zdorovya-chto-proishodit-s-individualnym-medicinskim-strahovaniem-v-ukraine

#!!nested element is not suported https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya: table

#darnitsya ficc.
https://mind.ua/en/publications/20183473-general-director-of-pharmaceutical-firm-darnitsa-import-substitution-is-nothing-more-than-anothe

#https://mind.ua/en/publications/20184607-life-elixir-how-a-pharmaceutical-company-launched-the-production-of-infusions
#figcaption

!figcaption is missing https://mind.ua/news/20194120-travmovanij-cherez-krosivok-nike-basketbolist-mozhe-otrimati-8-mln-strahovki

#related! : https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij
#!nested element to support
https://mind.ua/publications/20193089-nichogo-osobistogo-5-ted-vistupiv-pro-sheringovu-ekonomiku

#https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij
#mind.ua http://prntscr.com/mnqwci

#related links dynamicly changing
#https://mind.ua/ru/publications/20177078-chelovek-nedeli-hyu-hefner-tot-kto-sdelal-mir-svobodnym
№https://prnt.sc/mnqy7r
Channel Must to be set Min.ua not mind.live channel
2 authors is missing

!!https://mind.ua/news/20194347-zapravilas-u-prozorro-skilki-vitratila-derzhava-byudzhetnih-koshtiv-na-palne
figc missing maybe convert to ficaption

#tables maybe convert
https://mind.ua/ru/publications/20172756-gonka-na-vyzhivanie-rejting-strahovyh-kompanij-2017


https://mind.ua/news/20194347-zapravilas-u-prozorro-skilki-vitratila-derzhava-byudzhetnih-koshtiv-na-palne
Figcaptions are missing while they are possible to indentfiy.
Html struct:
http://prntscr.com/mu5ar6

https://mind.ua/news/20194293-youcontrol-tretinu-dohodu-biznesu-dnipropetrovshchini-ta-odeshchini-generuyut-ofshorni-kompaniyi
h6 maybe figcapt

#static pages https://mind.ua/editorial
#https://mind.ua/ads

#diff figcaptions
#https://mind.ua/publications/20193607-mi-z-it-kudi-piti-vchitisya-na-programista-u-2019-roci

#reclama link
#https://mind.ua/publications/20191791-navishcho-ukrayinskij-kompaniyi-vidkrivati-vlasnu-it-shkolu-ta-bezkoshtovno-navchati-lyudej

#2 authors:
#https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij

#iframe src https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven
#events page
#https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven
#
#!!
https://mind.ua/shield after reideriv
#https://mind.ua/openmind/20193742-8-mlrd-neefektivnosti-abo-chomu-ukrayinci-platyat-za-perevitrati-u-svinarstvi
#optional read more

https://mind.ua/ru/publications/20172756-gonka-na-vyzhivanie-rejting-strahovyh-kompanij-2017
check for generateion
2 authors https://mind.ua/ru/publications/20173816-strahovoj-sluchaj-pochemu-kompanii-yuriya-yavtushenko-lishili-licenzij

#https://mind.ua/ru/publications/20193751-dengi-na-svalke-pochemu-stoit-stroit-biotec-v-ukraine

 #related articles
 https://mind.ua/openmind/20193742-8-mlrd-neefektivnosti-abo-chomu-ukrayinci-platyat-za-perevitrati-u-svinarstvi



https://mind.ua/publications/20193961-grupovij-portret-v-intereri-7-zapitan-do-privatbanku
читайте-також плохо выделянемый
может структуру https://mind.ua/ru/publications/20193715-kak-izbavitsya-ot-mirovoj-problemy-s-plastikom-dilemma-krupnogo-biznesa
http://prntscr.com/mp886s

  !large tables
  https://mind.ua/ru/publications/20186445-rejting-strahovyh-kompanij-2018-kak-rynok-strahovshchikov-v-ukraine-vyhodit-iz-zastoya

sorry for duplicate. issue.
just did not have time to  all text:
so Next time dont forget to support this static pages:
/about
/ads
/editorial
/shield

and maybe even event this
static page /questions/385-integrities
http://prntscr.com/mskfco

All this pages are not obligatory, (at first sight)
but may became advantage sometime in decisive moment

just returning to you favor, to Not set issue at last minutes.
Good luck!


<div>: //blockquote[.//img]
<div>: //blockquote[.//table]
<div>: //blockquote[.//iframe]
<div>: //blockquote[.//video]
<div>: //blockquote[.//embed]
<div>: //blockquote[.//audio]

<div>: //p[.//img]
<div>: //p[.//table]
<div>: //p[.//iframe]
<div>: //p[.//video]
<div>: //p[.//audio]
<div>: //p[.//embed]
