#mind ua is not present
https://mind.ua/editorial
:)
Illya pishnyak 
https://mind.ua/publications/20193961-grupovij-portret-v-intereri-7-zapitan-do-privatbanku
related dynamic block

#партнерський матеріал
is like Information Is on advertise rights.
important to keep this link for user.

here is about festival
here for ex about Kyivstar company
https://mind.ua/publications/20192122-yak-kiyivstar-pidsadiv-kosmo-ta-shche-50-kompanij-na-veliki-dani

https://mind.ua/news/20194388-u-bryusseli-projde-festival-ukrayinskoyi-kulturi-ukrayinska-vesna


https://mind.ua/openmind/20189763-chomu-venchurnij-kapital-ominae-ukrayinskij-rinok
should be preserved

Agiw blockqoute
https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya
sunny with uzlVer

https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya

#old 2 aut
#test
https://mind.ua/openmind/20194151-u-zoni-turbulentnosti-yak-koncesiya-dopomozhe-ukrayinskim-aeroportam
!FIGcaption
fl:
https://mind.ua/openmind/20175907-hochu-selfi-ale-fotokameru-shche-ne-vinajshli-istoriya-viniknennya-ukrayinskogo-portretu

figc
https://mind.ua/en/publications/20190743-power-trends-what-energy-projects-are-worth-investing-in


should be precent cite
https://mind.ua/publications/20180681-tiha-gavan-shcho-dp-world-pridbala-v-portu-yuzhnij

https://mind.ua/openmind/20177349-korupciya-po-kiyivski-shcho-yavlyali-soboyu-habari-chasiv-getmanshchini
_fr right
https://mind.ua/openmind/20177349-korupciya-po-kiyivski-shcho-yavlyali-soboyu-habari-chasiv-getmanshchini

UzVer template better https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven

#support this static page
https://mind.ua/questions/385-integrities#3
#marked text
https://mind.ua/ru/publications/20193696-kilovatty-pod-zashchitoj-kak-zastrahovat-elektromobil
#marked text
https://mind.ua/ru/publications/20192337-cena-zdorovya-chto-proishodit-s-individualnym-medicinskim-strahovaniem-v-ukraine

#!!nested element is not suported https://mind.ua/publications/20192669-rozumnij-zahist-yak-zaoshchaditi-na-strahuvanni-avtomobilya: table

#darnitsya ficc.
https://mind.ua/en/publications/20183473-general-director-of-pharmaceutical-firm-darnitsa-import-substitution-is-nothing-more-than-anothe 

#https://mind.ua/en/publications/20184607-life-elixir-how-a-pharmaceutical-company-launched-the-production-of-infusions
#figcaption

!figcaption is missing https://mind.ua/news/20194120-travmovanij-cherez-krosivok-nike-basketbolist-mozhe-otrimati-8-mln-strahovki

#related! : https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij
#!nested element to support
https://mind.ua/publications/20193089-nichogo-osobistogo-5-ted-vistupiv-pro-sheringovu-ekonomiku

#https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij
#mind.ua http://prntscr.com/mnqwci

#related links dynamicly changing
#https://mind.ua/ru/publications/20177078-chelovek-nedeli-hyu-hefner-tot-kto-sdelal-mir-svobodnym
№https://prnt.sc/mnqy7r
Channel Must to be set Min.ua not mind.live channel
2 authors is missing

!!https://mind.ua/news/20194347-zapravilas-u-prozorro-skilki-vitratila-derzhava-byudzhetnih-koshtiv-na-palne
figc missing maybe convert to ficaption

#tables maybe convert
https://mind.ua/ru/publications/20172756-gonka-na-vyzhivanie-rejting-strahovyh-kompanij-2017


https://mind.ua/news/20194293-youcontrol-tretinu-dohodu-biznesu-dnipropetrovshchini-ta-odeshchini-generuyut-ofshorni-kompaniyi
h6 maybe figcapt

#static pages https://mind.ua/editorial
#https://mind.ua/ads

#diff figcaptions
#https://mind.ua/publications/20193607-mi-z-it-kudi-piti-vchitisya-na-programista-u-2019-roci

#reclama link
#https://mind.ua/publications/20191791-navishcho-ukrayinskij-kompaniyi-vidkrivati-vlasnu-it-shkolu-ta-bezkoshtovno-navchati-lyudej

#2 authors:
#https://mind.ua/publications/20184607-eliksir-zhittya-yak-farmacevtichna-firma-darnicya-stvoryuvala-virobnictvo-infuzij

#iframe src https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven
#events page
#https://mind.ua/education/934-vnutrishni-komunikaciyi-dlya-vlasnikiv-strategichnij-riven
#
#!!
https://mind.ua/shield after reideriv
#https://mind.ua/openmind/20193742-8-mlrd-neefektivnosti-abo-chomu-ukrayinci-platyat-za-perevitrati-u-svinarstvi
#optional read more

https://mind.ua/ru/publications/20172756-gonka-na-vyzhivanie-rejting-strahovyh-kompanij-2017
check for generateion
2 authors https://mind.ua/ru/publications/20173816-strahovoj-sluchaj-pochemu-kompanii-yuriya-yavtushenko-lishili-licenzij

#https://mind.ua/ru/publications/20193751-dengi-na-svalke-pochemu-stoit-stroit-biotec-v-ukraine
 
 #related articles
 https://mind.ua/openmind/20193742-8-mlrd-neefektivnosti-abo-chomu-ukrayinci-platyat-za-perevitrati-u-svinarstvi



https://mind.ua/publications/20193961-grupovij-portret-v-intereri-7-zapitan-do-privatbanku
читайте-також плохо выделянемый
может структуру https://mind.ua/ru/publications/20193715-kak-izbavitsya-ot-mirovoj-problemy-s-plastikom-dilemma-krupnogo-biznesa
http://prntscr.com/mp886s
  
  !large tables
  https://mind.ua/ru/publications/20186445-rejting-strahovyh-kompanij-2018-kak-rynok-strahovshchikov-v-ukraine-vyhodit-iz-zastoya

sorry for duplicate. issue.
just did not have time to  all text:
so Next time dont forget to support this static pages: 
/about
/ads
/editorial
/shield

and maybe even event this
static page /questions/385-integrities
http://prntscr.com/mskfco

All this pages are not obligatory, (at first sight)
but may became advantage sometime in decisive moment

just returning to you favor, to Not set issue at last minutes.
Good luck!


<div>: //blockquote[.//img]
<div>: //blockquote[.//table]
<div>: //blockquote[.//iframe]
<div>: //blockquote[.//video]
<div>: //blockquote[.//embed]
<div>: //blockquote[.//audio]

<div>: //p[.//img]
<div>: //p[.//table]
<div>: //p[.//iframe]
<div>: //p[.//video]
<div>: //p[.//audio]
<div>: //p[.//embed]