similar: https://mind.ua/ru/publications/20194584-otpusk-bez-zabot-kak-poluchit-pomoshch-po-turisticheskoj-strahovke


mind uz sanny lane
https://mind.ua/news/20195874-lugansku-ta-sumsku-oblasti-zalishili-bez-ukrayinskogo-telebachennya-ta-radio-zmi

empty p

dont fk with figcaptions 
https://mind.ua/ru/publications/20178608-mirovoj-rynok-it-mesto-ukrainy-na-nem not use


https://mind.ua/openmind/20185257-divis-instrukciyu-chomu-slid-obovyazkovo-oznajomitisya-z-tvorom-ha-yun-changa


mark text
https://mind.ua/publications/20193696-kilovati-pid-zahistom-yak-zastrahuvati-elektromobil
sunnylane
cover video
https://mind.ua/video/20185970-7-spriyatlivih-dlya-figuri-mist

https://mind.ua/publications/20191789-mi-obiraemo-nas-obirayut-yak-pracyue-medichne-strahuvannya-dlya-korporativnih-klientiv
double dividers



Template #157 (by w3drt465
!https://mind.ua/publications/20191789-mi-obiraemo-nas-obirayut-yak-pracyue-medichne-strahuvannya-dlya-korporativnih-klientiv

https://mind.ua/ru/style/20195666-premera-nedeli-vulkan
figcaption is not


possible figcaptions (text should be small size)
https://mind.ua/ru/publications/20172505-zapret-rossijskih-vagonov-dejstvuyut-li-sankcii
https://mind.ua/ru/publications/20178608-mirovoj-rynok-it-mesto-ukrainy-na-nem

mark 
https://mind.ua/publications/20193696-kilovati-pid-zahistom-yak-zastrahuvati-elektromobil
sunnylane
cover video
https://mind.ua/video/20185970-7-spriyatlivih-dlya-figuri-mist

https://mind.ua/publications/20191789-mi-obiraemo-nas-obirayut-yak-pracyue-medichne-strahuvannya-dlya-korporativnih-klientiv
double dividers
set PATH=%PATH%;C:\Users\Bilalapka\Miniconda3C:\Users\Bilalapka\Miniconda3\Scripts;

Weidr
https://mind.ua/publications/20191789-mi-obiraemo-nas-obirayut-yak-pracyue-medichne-strahuvannya-dlya-korporativnih-klientiv


kos
https://mind.ua/ru/publications/20174671-sankcii-ne-dlya-vseh-reputaciya-kakih-mezhdunarodnyh-kompanij-stradaet-iz-za-raboty-v-krymu
sunny 
kostia
weider
https://mind.ua/ru/style/20195666-premera-nedeli-vulkan
photo captions is missed
because broken layout

https://mind.ua/ru/education/1009-strategicheskij-marketing-kak-sozdayutsya-brendy
так себе

<div class="img_box2_c" style="max-width: 750px;">
<!-- Here must be IMG, as in all normal articles with figures , but its Not -->, 
	<div class="img_source">
		Фото: https://ufd.ua/vulkan</div>
</div>
http://prntscr.com/nao4w7
because img